apiVersion: v1
kind: Pod
metadata:
  name: lab4-3-nginx
  namespace: default
  labels:
    lab: lab4-3
    app: nginx
spec:
  containers:
  - name: nginx
    image: openresty/openresty
    ports:
      - containerPort: 80
    env:
      - name: MY_MESSAGE
        value: "hello from env your env var!"
    volumeMounts:
      - name: conf
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: default.conf
      - name: conf
        mountPath: /usr/local/openresty/nginx/conf/nginx.conf
        subPath: nginx.conf
  volumes:
    - name: conf
      configMap:
          name: lab4-3-nginx-conf
