apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-nodeport
  namespace: default
  labels:
    lab: dep-1-deployment
spec:
  type: NodePort
  selector:
    app: nginx-deployment
    lab: dep-1-deployment
  ports:
  - port: 80
    targetPort: 80
