---
apiVersion: v1
kind: Pod
metadata:
  name: lab2-1
  namespace: default
  labels:
    name: lab2-1
    lab: lab2-1
spec:
  containers:
  - name: nginx-pod
    image: nginxdemos/hello:plain-text
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab2-1
  namespace: default
  labels:
    name: lab2-1
    lab: lab2-1
spec:
  type: ClusterIP
  selector:
    lab: lab2-1
  ports:
  - port: 80
    targetPort: 80
