apiVersion: v1
kind: Service
metadata:
  name: lab2-2
  namespace: default
  labels:
    name: lab2-2
    lab: lab2-2
spec:
  type: NodePort
  selector:
    lab: lab2-1
  ports:
  - port: 80
    targetPort: 80