apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-4-nginx-conf
  namespace: default
  labels:
    lab: lab4-4
data:
  default.conf: |
    server {
        listen 80;

        location / {
            default_type text/plain;
            expires -1;

            content_by_lua_block {
              ngx.say("running in pod: " .. os.getenv("MY_POD_NAME"))
              ngx.say("message from env var MY_MESSAGE:")
              ngx.say("    " .. os.getenv("MY_MESSAGE"))
              ngx.say("message from env var MY_GREETING:")
              ngx.say("    " .. os.getenv("MY_GREETING"))   
            }
       
            # return 200 'from env var ABC: \n';
        }
    }
  nginx.conf: |
    env MY_MESSAGE;
    env MY_GREETING;
    env MY_POD_NAME;

    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
        #                  '$status $body_bytes_sent "$http_referer" '
        #                  '"$http_user_agent" "$http_x_forwarded_for"';

        #access_log  logs/access.log  main;

        # See Move default writable paths to a dedicated directory (#119)
        # https://github.com/openresty/docker-openresty/issues/119
        client_body_temp_path /var/run/openresty/nginx-client-body;
        proxy_temp_path       /var/run/openresty/nginx-proxy;
        fastcgi_temp_path     /var/run/openresty/nginx-fastcgi;
        uwsgi_temp_path       /var/run/openresty/nginx-uwsgi;
        scgi_temp_path        /var/run/openresty/nginx-scgi;

        sendfile        on;
        #tcp_nopush     on;

        #keepalive_timeout  0;
        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
