apiVersion: v1
kind: Pod
metadata:
  name: lab4-4-nginx
  namespace: default
  labels:
    lab: lab4-4
    app: nginx
spec:
  containers:
  - name: nginx
    image: openresty/openresty
    ports:
      - containerPort: 80
    envFrom:
    - configMapRef:
        name: lab4-4-env-vars
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    volumeMounts:
      - name: conf
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: default.conf
      - name: conf
        mountPath: /usr/local/openresty/nginx/conf/nginx.conf
        subPath: nginx.conf
  volumes:
    - name: conf
      configMap:
          name: lab4-4-nginx-conf
