apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-2-nginx-conf
  namespace: default
  labels:
    lab: lab4-2
data:
  default.conf: |
    server {
        listen 80;

        root /www/data;

        location / {
        }
    }
