apiVersion: v1
kind: Service
metadata:
  name: lab4-2-nginx-clusterip
  namespace: default
  labels:
    lab: lab4-2
spec:
  type: ClusterIP
  selector:
    lab: lab4-2
    app: nginx
  ports:
  - port: 80
    targetPort: 80
