apiVersion: v1
kind: Pod
metadata:
  name: lab4-2-nginx
  namespace: default
  labels:
    lab: lab4-2
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name: conf
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: default.conf
      - name: www
        mountPath: /www/data
  volumes:
    - name: conf
      configMap:
          name: lab4-2-nginx-conf
    - name: www
      configMap:
          name: lab4-2-www-dir