apiVersion: v1
kind: Service
metadata:
  name: mixed-deployment-nodeport
  namespace: default
  labels:
    lab: dep-N-TODO
spec:
  type: NodePort
  selector:
    app: echo-deployment
    lab: dep-N-TODO
  ports:
  - port: 80
    targetPort: 80
