apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    lab: dep-1-deployment
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
        lab: dep-1-deployment
    spec:
      initContainers:
      - name: slow-down
        image: busybox
        command: ['sh', '-c', "sleep 30"]
      containers:
      - name: nginx-deployment
        image: hashicorp/http-echo
        args:
        - -text="hello from hashicorp http-echo container!!"
        - -listen=:80
        ports:
          - containerPort: 80
