---
apiVersion: v1
kind: Pod
metadata:
  name: lab2-1-nginx
  namespace: default
  labels:
    lab: lab2-1
    app: nginx-plain-text
spec:
  containers:
  - name: nginx
    image: nginxdemos/hello:plain-text
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab2-1-nginx-clusterip
  namespace: default
  labels:
    lab: lab2-1
spec:
  type: ClusterIP
  selector:
    lab: lab2-1
    app: nginx-plain-text
  ports:
  - port: 80
    targetPort: 80
