apiVersion: v1
kind: Service
metadata:
  name: lab2-2-nginx-nodeport
  namespace: default
  labels:
    lab: lab2-2
spec:
  type: NodePort
  selector:
    lab: lab2-1
    app: nginx-plain-text
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100