apiVersion: v1
kind: Pod
metadata:
  name: lab4-1-nginx
  namespace: default
  labels:
    lab: lab4-1
    app: nginx-plain-text
spec:
  containers:
  - name: nginx
    image: nginxdemos/hello:plain-text
    ports:
      - containerPort: 80
    volumeMounts:
      - name: conf
        mountPath: /etc/nginx/conf.d/hello-plain-text.conf
        subPath: hello-plain-text.conf
  volumes:
    - name: conf
      configMap:
          name: lab4-1-nginx-conf