apiVersion: v1
kind: Pod
metadata:
  name: lab3-1
  namespace: default
  labels:
    name: lab3-1
    app: lab3-1
    lab: lab3-1
spec:
  containers:
  - name: nginx
    image: nginxdemos/hello:plain-text
    ports:
      - containerPort: 80
    volumeMounts:
      - name: conf
        mountPath: /etc/nginx/conf.d/hello-plain-text.conf
        subPath: hello-plain-text.conf
  volumes:
    - name: conf
      configMap:
          name: lab3-1