apiVersion: v1
kind: ConfigMap
metadata:
  name: lab5-1-nginx-conf
  namespace: default
  labels:
    lab: lab5-1
data:
  default.conf: |
    server {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;

        location / {
            default_type text/plain;
            expires -1;
            return 200 'THIS SITE USES TLS!\nServer address: $server_addr:$server_port\nServer name: $hostname\nDate: $time_local\nURI: $request_uri\nRequest ID: $request_id\n';
        }
    }
