apiVersion: v1
kind: Pod
metadata:
  name: lab5-1-nginx
  namespace: default
  labels:
    lab: lab5-1
    app: nginx-tls
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 443
    volumeMounts:
      - name: conf
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: default.conf
      - name: certs
        mountPath: /etc/nginx/tls
  volumes:
    - name: conf
      configMap:
          name: lab5-1-nginx-conf
    - name: certs
      secret:
        secretName: lab5-1-tls