apiVersion: v1
kind: Service
metadata:
  name: lab5-1-tls
  namespace: default
  labels:
    lab: lab5-1
spec:
  type: ClusterIP
  selector:
    lab: lab5-1
    app: nginx-tls
  ports:
  - port: 443
    targetPort: 443
