apiVersion: v1
kind: Service
metadata:
  name: nginx-pod
  namespace: default
  labels:
    lab: svc-1-nginx-pod-2-pod
spec:
  type: ClusterIP
  selector:
    app: nginx-pod
    lab: svc-1-nginx-pod-2-pod
  ports:
  - port: 80
    targetPort: 80
