apiVersion: v1
kind: Pod
metadata:
  name: lab2-1-nginx
  namespace: default
  labels:
    lab: lab2-1
    app: nginx-plain-text
spec:
  containers:
  - name: nginx
    image: nginxdemos/hello:plain-text
    ports:
      - containerPort: 80