apiVersion: v1
kind: Service
metadata:
  name: lab2-1-nginx-clusterip
  namespace: default
  labels:
    lab: lab2-1
spec:
  type: ClusterIP
  selector:
    lab: lab2-1
    app: nginx-plain-text
  ports:
  - port: 80
    targetPort: 80
